# Version: 0.0.1
FROM ramwin/ubuntu_163_upgraded
MAINTAINER Xiang Wang "1175190234@qq.com"
RUN apt-get update
RUN apt-get -yqq upgrade
RUN apt-get install -y gnome-panel 
RUN apt-get install -y gnome-settings-daemon 
RUN apt-get install -y metacity 
RUN apt-get install -y nautilus 
RUN apt-get install -y gnome-terminal
