# Version: latest
From ubuntu:14.04
MAINTAINER Xiang Wang "1175190234@qq.com"
RUN rm -rf /etc/apt/sources.list
ADD sources.list /etc/apt/sources.list
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -yqq wget curl tree vim
